### ISSUE TITLE
Will you be accepting pull requests?

### ISSUE THREAD

**Issue by andy5995** [malessandrini/boswars-user-manual#1]
Boswars development has resumed (https://boswars.org/download.shtml). Will you be accepting pull requests on this repo? I see it's mentioned in the new [Boswars wiki on CodeBerg](https://codeberg.org/boswars/boswars/wiki).

**Comment by malessandrini** [comment]
Hi, I'm glad there is new interest. Of course I will accept pull requests, well I guess if they're not too out of context.

**Comment by andy5995** [comment]
Thank you, @malessandrini ! I don't have anything particular in mind yet. It seems you did an awesome job writing a comprehensive manual.

**Comment by malessandrini** [comment]
Thanks, actually I contacted boswars developers back then but had no reply, so I wrote it here. But if they like it and they want to use it I would have no problems.
BTW are you a boswars developer? Am I wrong or it seems like there is new development activity? Is there a way to be kept informed about that?

**Comment by andy5995** [comment]
So far I'm just a minor contributor, and have been participating in discussions in the `#boswars` channel on Libera chat and the [BosWars CodeBerg repo](https://codeberg.org/boswars/boswars), which is the new official repository. Yes, there's new development activity. feb, one of the original developers released 2.8 last week, and has started a branch to migrate the code to use SDL2 instead of SDL1.

So to be informed about new activity, you can "watch" the codeberg repo, and there's also an RSS feed shown on the repo. I think feb will be creating a Matrix room for boswars, but right now there's the IRC channel I mentioned.

**Comment by andy5995** [comment]
I've just been told by feb that ze has created an offical Boswars Matrix room: https://matrix.to/#/#boswars:matrix.org
