### ISSUE TITLE
Added to Bos Wars subreddit

### ISSUE THREAD

**Issue by andy5995** [malessandrini/boswars-user-manual#4]
Hi @malessandrini ! I added the link to your manual to https://www.reddit.com/r/boswars/comments/14wvskm/github_malessandriniboswarsusermanual/?utm_source=share&utm_medium=web2x&context=3

**Comment by malessandrini** [comment]
Great! Please notice that there is the Italian version, too.
Bye
Michele

**Comment by andy5995** [comment]
Ok, I added a note to the comments.
